package pojos;
// Generated 2019.01.20. 18:26:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Airport generated by hbm2java
 */
@Entity
@Table(name="airport"
    ,catalog="airports"
)
public class Airport  implements java.io.Serializable {


     private String code;
     private String name;
     private String countryCode;
     private Set<Route> routesForOrigin = new HashSet<Route>(0);
     private Set<Route> routesForDestination = new HashSet<Route>(0);

    public Airport() {
    }

	
    public Airport(String code, String name, String countryCode) {
        this.code = code;
        this.name = name;
        this.countryCode = countryCode;
    }
    public Airport(String code, String name, String countryCode, Set<Route> routesForOrigin, Set<Route> routesForDestination) {
       this.code = code;
       this.name = name;
       this.countryCode = countryCode;
       this.routesForOrigin = routesForOrigin;
       this.routesForDestination = routesForDestination;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="name", nullable=false, length=35)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="countryCode", nullable=false, length=3)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="airportByOrigin")
    public Set<Route> getRoutesForOrigin() {
        return this.routesForOrigin;
    }
    
    public void setRoutesForOrigin(Set<Route> routesForOrigin) {
        this.routesForOrigin = routesForOrigin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="airportByDestination")
    public Set<Route> getRoutesForDestination() {
        return this.routesForDestination;
    }
    
    public void setRoutesForDestination(Set<Route> routesForDestination) {
        this.routesForDestination = routesForDestination;
    }




}


