package pojos;
// Generated 2019.01.20. 18:26:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name="route"
    ,catalog="airports"
)
public class Route  implements java.io.Serializable {


     private int id;
     private Airport origin;
     private Airport destination;
     private String name;
     private int weight;
     private int weightNow;
     private boolean visited;

    public Route() {
    }

    public Route(int id, Airport airportByOrigin, Airport airportByDestination, String name, int weight, int weightNow, boolean visited) {
       this.id = id;
       this.origin = airportByOrigin;
       this.destination = airportByDestination;
       this.name = name;
       this.weight = weight;
       this.weightNow = weightNow;
       this.visited = visited;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="origin", nullable=false)
    public Airport getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(Airport origin) {
        this.origin = origin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="destination", nullable=false)
    public Airport getDestination() {
        return this.destination;
    }
    
    public void setDestination(Airport destination) {
        this.destination = destination;
    }

    
    @Column(name="name", nullable=false, length=35)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="weight", nullable=false)
    public int getWeight() {
        return this.weight;
    }
    
    public void setWeight(int weight) {
        this.weight = weight;
    }

    
    @Column(name="weightNow", nullable=false)
    public int getWeightNow() {
        return this.weightNow;
    }
    
    public void setWeightNow(int weightNow) {
        this.weightNow = weightNow;
    }

    
    @Column(name="visited", nullable=false)
    public boolean isVisited() {
        return this.visited;
    }
    
    public void setVisited(boolean visited) {
        this.visited = visited;
    }




}


