package pojos;
// Generated 2019.01.20. 18:26:07 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name = "route",
        catalog = "airports"
)
public class Route implements java.io.Serializable {

    private int id;
    private Airport airportByOrigin;
    private Airport airportByDestination;
    private String name;
    private int weight;
    private int weightNow;
    private boolean visited;

    public Route() {
    }

    public Route(int id, Airport airportByOrigin, Airport airportByDestination, String name, int weight, int weightNow, boolean visited) {
        this.id = id;
        this.airportByOrigin = airportByOrigin;
        this.airportByDestination = airportByDestination;
        this.name = name;
        this.weight = weight;
        this.weightNow = weightNow;
        this.visited = visited;
    }

    public Route(int id, Airport airportByOrigin, Airport airportByDestination, int weight, boolean visited) {
        this.id = id;
        this.airportByOrigin = airportByOrigin;
        this.airportByDestination = airportByDestination;
        this.name = name;
        this.weight = weight;
        this.weightNow = weightNow;
        this.visited = visited;
    }

    public Route(Airport airportByOrigin, Airport airportByDestination, int weight, boolean visited) {
        this.airportByOrigin = airportByOrigin;
        this.airportByDestination = airportByDestination;
        this.weight = weight;
        this.weightNow = weight;
        this.visited = visited;
    }

    public Route(Airport airportByOrigin, Airport airportByDestination, int weight) {
        this.airportByOrigin = airportByOrigin;
        this.airportByDestination = airportByDestination;
        this.weight = weight;
        this.weightNow = weight;
        this.visited = false;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "origin", nullable = false)
    public Airport getOrigin() {
        return this.airportByOrigin;
    }

    public void setOrigin(Airport airportByOrigin) {
        this.airportByOrigin = airportByOrigin;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "destination", nullable = false)
    public Airport getDestination() {
        return this.airportByDestination;
    }

    public void setDestination(Airport airportByDestination) {
        this.airportByDestination = airportByDestination;
    }

    @Column(name = "name", nullable = false, length = 35)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "weight", nullable = false)
    public int getWeight() {
        return this.weight;
    }

    public void setWeight(int weight) {
        this.weight = weight;
    }

    @Column(name = "weightNow", nullable = false)
    public int getWeightNow() {
        return this.weightNow;
    }

    public void setWeightNow(int weightNow) {
        this.weightNow = weightNow;
    }

    @Column(name = "visited", nullable = false)
    public boolean isVisited() {
        return this.visited;
    }

    public void setVisited(boolean visited) {
        this.visited = visited;
    }

    @Override
    public String toString() {
        return airportByOrigin + "-" + airportByDestination;
    }

}
